// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tszsmthiqnzwkytrqbtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzenNtdGhpcW56d2t5dHJxYnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTA5MTAsImV4cCI6MjA2NzQ2NjkxMH0.juTGxOhDkGfw69zsTjsWa-NvS9v93hGzSvGGA5gLd9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});